/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.gss.lang.iface.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IFACEUiModule extends AbstractIFACEUiModule {

	public IFACEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
