/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.gss.lang.iface;

import org.eclipse.xtext.linking.ILinker;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

import es.uah.aut.srg.gss.xtext.GSSDescriptionAssociator;
import es.uah.aut.srg.gss.xtext.GSSLazyLinker;
import es.uah.aut.srg.gss.xtext.GSSQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IFACERuntimeModule extends AbstractIFACERuntimeModule {	
	
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return GSSQualifiedNameProvider.GSSDefaultNameConverter.class;
	}
	
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {  
		return GSSQualifiedNameProvider.class;
	}
	
	public Class<? extends GSSDescriptionAssociator> bindDescriptionAssociator() {
		return GSSDescriptionAssociator.class;
	}
	
	public Class<? extends ILinker> bindILinker() {
		return GSSLazyLinker.class;
	}
}
