/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.gss.lang.iface;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IFACEStandaloneSetup extends IFACEStandaloneSetupGenerated {

	public static void doSetup() {
		new IFACEStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
}
