<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="campaign" nsURI="http://srg.aut.uah.es/gss/campaign" nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EClass" name="GSSCampaignCampaign" eSuperTypes="common.ecore#//GSSModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" lowerBound="1"
        eType="ecore:EClass environment.ecore#//GSSEnvironmentScenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" lowerBound="1" eType="#//GSSCampaignTests"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSCampaignTests">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" upperBound="150"
        eType="#//GSSCampaignTest" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSCampaignTestReqAction">
    <eLiterals name="_1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSCampaignTest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" lowerBound="1"
        eType="ecore:EClass test_proc.ecore#//GSSTestProcTestProc"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="req" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reqAction" eType="#//GSSCampaignTestReqAction"
        unsettable="true"/>
  </eClassifiers>
</ecore:EPackage>
