<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="config" nsURI="http://srg.aut.uah.es/gss/config" nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGSSConfig" eSuperTypes="common.ecore#//GSSModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gss_options" lowerBound="1"
        eType="#//GSSConfigGSSOptions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Protocols" lowerBound="1"
        eType="#//GSSConfigProtocols" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Interfaces" lowerBound="1"
        eType="#//GSSConfigInterfaces" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SpecialPackets" eType="#//GSSConfigSpecialPackets"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PeriodicTCs" eType="#//GSSConfigPeriodicTCs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GlobalVars" eType="#//GSSConfigGlobalVars"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Monitors" eType="#//GSSConfigMonitors"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tests" lowerBound="1" eType="#//GSSConfigTests"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGSSOptions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gss_info" lowerBound="1"
        eType="#//GSSConfigGSSInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gss_info_print" lowerBound="1"
        eType="#//GSSConfigGSSInfoPrint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phy_header_print" lowerBound="1"
        eType="#//GSSConfigPhyHeaderPrint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discardErrorFlags" lowerBound="1"
        eType="#//GSSConfigGSSDiscardErrorFlags" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigEnableDisable">
    <eLiterals name="disabled"/>
    <eLiterals name="enabled" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGSSInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test_campaign" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version_control_url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGSSInfoPrint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainLog" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portLogs" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawLog" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPhyHeaderPrint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainLog" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portLogs" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawLog" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gssTabs" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGSSDiscardErrorFlags">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="txErrors" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notExpectedPackets" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filtersKo" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTimesKo" lowerBound="1"
        eType="#//GSSConfigEnableDisable" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigProtocols">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Protocol" lowerBound="1"
        upperBound="2" eType="#//GSSConfigProtocol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigProtocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLevel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeOffset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtypeOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigInterfaces">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MainInterface" lowerBound="1"
        eType="#//GSSConfigMainInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Interface" upperBound="7"
        eType="#//GSSConfigInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigMainInterfaceType">
    <eLiterals name="SpW"/>
    <eLiterals name="uart" value="1"/>
    <eLiterals name="dummy" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigMainInterfaceIOType">
    <eLiterals name="in_out"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigMainInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifType" lowerBound="1"
        eType="#//GSSConfigMainInterfaceType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConfig" lowerBound="1"
        eType="ecore:EClass iface.ecore#//GSSIfacePortConfig"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ioType" lowerBound="1"
        eType="#//GSSConfigMainInterfaceIOType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocolID" eType="#//GSSConfigProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LevelInOut" lowerBound="1"
        upperBound="3" eType="#//GSSConfigLevelInOut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigInterfaceType">
    <eLiterals name="SpW"/>
    <eLiterals name="SpW_TC" value="1"/>
    <eLiterals name="SpW_Error" value="2"/>
    <eLiterals name="uart" value="3"/>
    <eLiterals name="dummy" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigInterfaceIOType">
    <eLiterals name="in_out"/>
    <eLiterals name="in" value="1"/>
    <eLiterals name="out" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifType" lowerBound="1"
        eType="#//GSSConfigInterfaceType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifConfig" lowerBound="1"
        eType="ecore:EClass iface.ecore#//GSSIfacePortConfig"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ioType" lowerBound="1"
        eType="#//GSSConfigInterfaceIOType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocolID" eType="#//GSSConfigProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LevelInOut" upperBound="3"
        eType="#//GSSConfigLevelInOut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LevelIn" upperBound="3"
        eType="#//GSSConfigLevelIn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LevelOut" upperBound="3"
        eType="#//GSSConfigLevelOut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigLevelInOut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMformat" lowerBound="1"
        eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TCformat" lowerBound="1"
        eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFilter" lowerBound="1"
        eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="export_to_prev_Level" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import_from_prev_Level"
        eType="ecore:EClass imports.ecore#//GSSImportImport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigLevelIn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TCformat" lowerBound="1"
        eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="export_to_prev_Level" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigLevelOut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMformat" lowerBound="1"
        eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFilter" lowerBound="1"
        eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import_from_prev_Level"
        eType="ecore:EClass imports.ecore#//GSSImportImport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigSpecialPackets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SpecialPacket" lowerBound="1"
        upperBound="17" eType="#//GSSConfigSpecialPacket" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigSpecialPacket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//GSSConfigEnableDisable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFilter" lowerBound="1"
        eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UpperLevels" upperBound="3"
        eType="#//GSSConfigUpperLevels" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="printingData" lowerBound="1"
        eType="#//GSSConfigPrintingData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="period" eType="#//GSSConfigPeriod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervalRange" eType="#//GSSConfigIntervalRange"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigUpperLevels">
    <eStructuralFeatures xsi:type="ecore:EReference" name="UpperLevel" lowerBound="1"
        upperBound="-1" eType="#//GSSConfigUpperLevel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigUpperLevelLevel">
    <eLiterals name="_1"/>
    <eLiterals name="_2" value="1"/>
    <eLiterals name="_3" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigUpperLevel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="#//GSSConfigUpperLevelLevel"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TMformat" lowerBound="1"
        eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFilter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import_from_prev_Level"
        eType="ecore:EClass imports.ecore#//GSSImportImport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPrintingData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="printStatus" lowerBound="1"
        eType="#//GSSConfigEnableDisable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredData" eType="#//GSSConfigStructuredData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigStructuredData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstField" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigUnit">
    <eLiterals name="miliseconds"/>
    <eLiterals name="seconds" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPeriod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_unit" lowerBound="1"
        eType="#//GSSConfigUnit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_unit" lowerBound="1"
        eType="#//GSSConfigUnit" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigIntervalRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval_unit" lowerBound="1"
        eType="#//GSSConfigUnit" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPeriodicTCs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PeriodicTC_level_2" upperBound="-1"
        eType="#//GSSConfigPeriodicTCLevel2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PeriodicTC_level_1" upperBound="-1"
        eType="#//GSSConfigPeriodicTCLevel1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PeriodicTC_level_0" upperBound="-1"
        eType="#//GSSConfigPeriodicTCLevel0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPeriodicTCLevel2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_unit" lowerBound="1"
        eType="#//GSSConfigUnit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level2" lowerBound="1"
        eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_to_level1" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPeriodicTCLevel1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_unit" lowerBound="1"
        eType="#//GSSConfigUnit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level1" lowerBound="1"
        eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPeriodicTCLevel0">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_unit" lowerBound="1"
        eType="#//GSSConfigUnit" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level0" lowerBound="1"
        eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGlobalVars">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GlobalVar" lowerBound="1"
        upperBound="10" eType="#//GSSConfigGlobalVar" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigGlobalVarType">
    <eLiterals name="uint"/>
    <eLiterals name="formula" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGlobalVar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSConfigGlobalVarType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceField" eType="#//GSSConfigReferenceField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencePeriodicTC" eType="#//GSSConfigReferencePeriodicTC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceSpecialPacket"
        eType="#//GSSConfigReferenceSpecialPacket" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigReferenceFieldType">
    <eLiterals name="tm"/>
    <eLiterals name="tc" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigReferenceField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSConfigReferenceFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigReferencePeriodicTC">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigReferenceSpecialPacket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigMonitors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChartsFile" eType="ecore:EClass charts.ecore#//GSSChartsCharts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plot" upperBound="-1" eType="#//GSSConfigPlot"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alarmMsg" upperBound="-1"
        eType="#//GSSConfigAlarmMsg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modify" upperBound="-1"
        eType="#//GSSConfigModify" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alarmVal" upperBound="3"
        eType="#//GSSConfigAlarmVal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigPlot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chartRef" lowerBound="1"
        eType="ecore:EClass charts.ecore#//GSSChartsChart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVFiltered" eType="#//GSSConfigGVFiltered"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVPeriodic" eType="#//GSSConfigGVPeriodic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigAlarmMsgType">
    <eLiterals name="alarm1"/>
    <eLiterals name="alarm2" value="1"/>
    <eLiterals name="alarm3" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigAlarmMsg">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSConfigAlarmMsgType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVFiltered" eType="#//GSSConfigGVFiltered"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVPeriodic" eType="#//GSSConfigGVPeriodic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigModifyType">
    <eLiterals name="increment"/>
    <eLiterals name="increment1wrap" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigModify">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSConfigModifyType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVFiltered" eType="#//GSSConfigGVFiltered"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVPeriodic" eType="#//GSSConfigGVPeriodic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigAlarmValType">
    <eLiterals name="alarm1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigAlarmVal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSConfigAlarmValType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVFiltered" eType="#//GSSConfigGVFiltered"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GVPeriodic" eType="#//GSSConfigGVPeriodic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGVFiltered">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GlobalVarRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigGVPeriodic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GlobalVarRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period_unit" lowerBound="1"
        eType="#//GSSConfigUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigTests">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProtocolPacketsFile" eType="ecore:EClass protocol_packets.ecore#//GSSProtocolPacketsProtocolPackets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestCase" lowerBound="1"
        upperBound="150" eType="#//GSSConfigTestCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSConfigReqAction">
    <eLiterals name="_1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSConfigTestCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" lowerBound="1"
        eType="ecore:EClass test_proc.ecore#//GSSTestProcTestProc"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="req" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reqAction" eType="#//GSSConfigReqAction"
        unsettable="true"/>
  </eClassifiers>
</ecore:EPackage>
