<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tc" nsURI="http://srg.aut.uah.es/gss/tc" nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EClass" name="GSSTC" eSuperTypes="../../es.uah.aut.srg.tmtcif/model/tc.ecore#//TMTCIFTC">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to_level3_export" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_format" eType="ecore:EClass format.ecore#//GSSFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to_level2_export" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_format" eType="ecore:EClass format.ecore#//GSSFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to_level1_export" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_format" eType="ecore:EClass format.ecore#//GSSFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to_level0_export" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_format" eType="ecore:EClass format.ecore#//GSSFormatFormat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTCField" eSuperTypes="../../es.uah.aut.srg.tmtcif/model/tc.ecore#//TMTCIFTCField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gssField" lowerBound="1"
        eType="ecore:EClass format.ecore#//GSSFormatField"/>
  </eClassifiers>
</ecore:EPackage>
