<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_campaign" nsURI="http://srg.aut.uah.es/gss/test_campaign"
    nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestCampaignTestCampaign">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" lowerBound="1" upperBound="150"
        eType="#//GSSTestCampaignTest" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestCampaignTest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedure" lowerBound="1"
        eType="ecore:EClass test_proc.ecore#//GSSTestProcTestProc" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevMsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevAction" eType="ecore:EEnum test_proc.ecore#//GSSTestProcPrevAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevActionParam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
