<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_proc" nsURI="http://srg.aut.uah.es/gss/test_proc" nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcTestProc" eSuperTypes="common.ecore#//GSSModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" lowerBound="1" upperBound="1900"
        eType="#//GSSTestProcStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTestProcMode">
    <eLiterals name="continuous"/>
    <eLiterals name="manual" value="1"/>
    <eLiterals name="concurrent" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcStep" eSuperTypes="common.ecore#//GSSModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="#//GSSTestProcMode"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prev_step_idref" eType="#//GSSTestProcStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_idref_from_prev_step"
        eType="#//GSSTestProcOutput"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        eType="#//GSSTestProcInputs" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" eType="#//GSSTestProcOutputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialPackets" eType="#//GSSTestProcSpecialPackets"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concurrent_steps" eType="#//GSSTestProcConcurrentSteps"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_3" upperBound="-1"
        eType="#//GSSTestProcInputLevel3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_2" upperBound="-1"
        eType="#//GSSTestProcInputLevel2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_1" upperBound="-1"
        eType="#//GSSTestProcInputLevel1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_0" upperBound="-1"
        eType="#//GSSTestProcInputLevel0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTestProcUnit">
    <eLiterals name="miliseconds"/>
    <eLiterals name="seconds" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTestProcCheckmode">
    <eLiterals name="all"/>
    <eLiterals name="allunsorted" value="1"/>
    <eLiterals name="any" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutputs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkmode" lowerBound="1"
        eType="#//GSSTestProcCheckmode" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid_time_interval_value"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid_time_interval_unit"
        lowerBound="1" eType="#//GSSTestProcUnit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_3" upperBound="-1"
        eType="#//GSSTestProcOutputLevel3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_2" upperBound="-1"
        eType="#//GSSTestProcOutputLevel2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_1" upperBound="-1"
        eType="#//GSSTestProcOutputLevel1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_0" upperBound="-1"
        eType="#//GSSTestProcOutputLevel0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcSpecialPackets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enable" upperBound="-1"
        eType="#//GSSTestProcEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disable" upperBound="-1"
        eType="#//GSSTestProcEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enable_print" upperBound="-1"
        eType="#//GSSTestProcEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disable_print" upperBound="-1"
        eType="#//GSSTestProcEnableDisable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcEnableDisable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTestProcYesNo">
    <eLiterals name="yes"/>
    <eLiterals name="no" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcConcurrentSteps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStep" lowerBound="1"
        eType="#//GSSTestProcNextStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concurrent_step" lowerBound="1"
        upperBound="-1" eType="#//GSSTestProcConcurrentStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcNextStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" lowerBound="1"
        eType="#//GSSTestProcYesNo" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcConcurrentStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_unit" lowerBound="1"
        eType="#//GSSTestProcUnit" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInputLevel3" eSuperTypes="#//GSSTestProcInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level3" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_to_level2" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_to_level1" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInputLevel2" eSuperTypes="#//GSSTestProcInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level2" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_to_level1" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInputLevel1" eSuperTypes="#//GSSTestProcInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level1" eType="ecore:EClass export.ecore#//GSSExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcInputLevel0" eSuperTypes="#//GSSTestProcInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level0" eType="ecore:EClass export.ecore#//GSSExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutput" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutputLevel3" eSuperTypes="#//GSSTestProcOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_filter" lowerBound="1"
        eType="#//GSSTestProcLevel3Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_from_level2" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_filter" lowerBound="1"
        eType="#//GSSTestProcLevel2Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_from_level1" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//GSSTestProcLevel1Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//GSSTestProcLevel0Filter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutputLevel2" eSuperTypes="#//GSSTestProcOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_filter" lowerBound="1"
        eType="#//GSSTestProcLevel2Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_from_level1" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//GSSTestProcLevel1Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//GSSTestProcLevel0Filter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutputLevel1" eSuperTypes="#//GSSTestProcOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//GSSTestProcLevel1Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass imports.ecore#//GSSImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//GSSTestProcLevel0Filter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcOutputLevel0" eSuperTypes="#//GSSTestProcOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass tm_tc_format.ecore#//GSSTmTcFormatTmTcFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//GSSTestProcLevel0Filter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcLevel3Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply_def_filter" lowerBound="1"
        eType="#//GSSTestProcYesNo" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_filter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcLevel2Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply_def_filter" lowerBound="1"
        eType="#//GSSTestProcYesNo" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_filter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcLevel1Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply_def_filter" lowerBound="1"
        eType="#//GSSTestProcYesNo" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_filter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTestProcLevel0Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply_def_filter" lowerBound="1"
        eType="#//GSSTestProcYesNo" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_filter" eType="ecore:EClass filters.ecore#//GSSFilterFilter"/>
  </eClassifiers>
</ecore:EPackage>
