<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tm_tc_format" nsURI="http://srg.aut.uah.es/gss/tm_tc_format"
    nsPrefix="gss">
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatTmTCFormatType">
    <eLiterals name="TM" literal="TM"/>
    <eLiterals name="TC" value="1" literal="TC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatTmTCFormat" eSuperTypes="common.ecore#//GSSModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatTmTCFormatType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CSField" upperBound="-1"
        eType="#//GSSTmTcFormatCSField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CSFormulaField" upperBound="-1"
        eType="#//GSSTmTcFormatCSFormulaField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VSField" upperBound="-1"
        eType="#//GSSTmTcFormatVSField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FDICField" upperBound="-1"
        eType="#//GSSTmTcFormatFDICField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VRFieldSize" upperBound="-1"
        eType="#//GSSTmTcFormatVRFieldSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AField" upperBound="-1"
        eType="#//GSSTmTcFormatAField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AIField" upperBound="-1"
        eType="#//GSSTmTcFormatAIField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatFieldType">
    <eLiterals name="structured" literal="structured"/>
    <eLiterals name="uint" value="1" literal="uint"/>
    <eLiterals name="flag" value="2" literal="flag"/>
    <eLiterals name="enumerated" value="3" literal="enumerated"/>
    <eLiterals name="bit_vector" value="4" literal="bit_vector"/>
    <eLiterals name="byte_vector" value="5" literal="byte_vector"/>
    <eLiterals name="float" value="6" literal="float"/>
    <eLiterals name="deduced" value="7" literal="deduced"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatFieldByteOrder">
    <eLiterals name="big_endian" literal="big_endian"/>
    <eLiterals name="little_endian" value="1" literal="little_endian"/>
    <eLiterals name="na" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatSFieldFirstBit">
    <eLiterals name="MSB" literal="MSB"/>
    <eLiterals name="LSB" value="1" literal="LSB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatCheckType">
    <eLiterals name="crc16"/>
    <eLiterals name="checksum16" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatField" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatCSField" eSuperTypes="#//GSSTmTcFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//GSSTmTcFormatSize"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//GSSTmTcFormatGlobalOffset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatCSFormulaField" eSuperTypes="#//GSSTmTcFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//GSSTmTcFormatSize"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//GSSTmTcFormatGlobalOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//GSSTmTcFormatFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatVSField" eSuperTypes="#//GSSTmTcFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constSize" lowerBound="1"
        eType="#//GSSTmTcFormatConstSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//GSSTmTcFormatGlobalOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxSize" lowerBound="1"
        eType="#//GSSTmTcFormatMaxSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableSize" lowerBound="1"
        eType="#//GSSTmTcFormatVariableSize" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatVRFieldSize" eSuperTypes="#//GSSTmTcFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatFDICField" eSuperTypes="#//GSSTmTcFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkType" lowerBound="1"
        eType="#//GSSTmTcFormatCheckType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//GSSTmTcFormatSize"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatingOffset" lowerBound="1"
        eType="#//GSSTmTcFormatFloatingOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortedFieldsToCheck" lowerBound="1"
        eType="#//GSSTmTcFormatSortedFieldsToCheck" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatAField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//GSSTmTcFormatSize"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//GSSTmTcFormatGlobalOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayDimension" lowerBound="1"
        eType="#//GSSTmTcFormatArrayDimension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatAIField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GSSTmTcFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//GSSTmTcFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//GSSTmTcFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//GSSTmTcFormatSize"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localOffset" lowerBound="1"
        eType="#//GSSTmTcFormatLocalOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayRef" lowerBound="1"
        eType="#//GSSTmTcFormatArrayRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatGlobalOffset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slope" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intercept" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatConstSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatUnit">
    <eLiterals name="bytes"/>
    <eLiterals name="bits" value="1"/>
    <eLiterals name="halfword" value="2"/>
    <eLiterals name="string10" value="3"/>
    <eLiterals name="string17" value="4"/>
    <eLiterals name="string69" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GSSTmTcFormatPower">
    <eLiterals name="_2" literal="2"/>
    <eLiterals name="_2_with_0" value="1" literal="2_with_0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatVariableSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//GSSTmTcFormatUnit"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="#//GSSTmTcFormatPower"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatMaxSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatFloatingOffset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatSortedFieldsToCheck">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldToCheck" upperBound="-1"
        eType="#//GSSTmTcFormatFieldToCheck" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatFieldToCheck">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatArrayDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatArrayRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSSTmTcFormatLocalOffset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
