/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.gss.lang.iface.scoping;

import es.uah.aut.srg.gss.xtext.GSSAbstractScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class IFACEScopeProvider extends GSSAbstractScopeProvider {
}